language: r
sudo: required
before_install: R -e
'source("https://install-github.me/r-lib/remotes")'

### see https://github.com/r-lib/devtools/issues/2020

# Be strict when checking our package
# warnings_are_errors: true
